### ISSUE TITLE
module 'cv2.cv2' has no attribute 'face'

### ISSUE THREAD

**Issue by scopolamin** [Jabrils/TelloTV#3]
Traceback (most recent call last):
  File "tellotv.py", line 46, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

**Comment by D-M-Moriarty** [comment]
I had the exact same issue

**Comment by scopolamin** [comment]
@D-M-Moriarty Did you find a solution?

**Comment by Jabrils** [comment]
Check the requirements.txt, you need to install the contribute-opencv version. I would install both just to be sure. This should fix your problem.

**Comment by MaximeDeleau** [comment]
I have the same issue even with opencv-contrib installed via the install command you provided.

**Comment by MaximeDeleau** [comment]
I managed to make it work. 
I uninstalled opencv-contrib using this command : 

> `pip uninstall opencv_contrib_python`

And reinstalled it using : 

> `pip install opencv_contrib_python`

Thank you Jabrils for this project and the videos associated. You now have another subscriber.

**Comment by Rupesh-Ghimire** [comment]
Traceback (most recent call last):
  File "/home/rupesh/PycharmProjects/Face_Recognition_Classroom_attendence/training.py", line 4, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

Process finished with exit code 1
I am getting the same problem even after uninstalling and installing the opencv-contrib

**Comment by themrcesi** [comment]
Uninstall and install opencv-contrib-python worked for me.

**Comment by Klatuu82** [comment]
i made it on my system, by only updating the contrib on the newest Version.
Hope anyone helps this

**Comment by kadrim** [comment]
> i made it on my system, by only updating the contrib on the newest Version.
> Hope anyone helps this

this did it for me.

the command involved is:

```
pip install --upgrade opencv_contrib_python
```

this pulled-in: opencv_contrib_python-4.1.1.26-cp37-cp37m-win_amd64.whl on my system

**Comment by thegloriousblip** [comment]
pip3 uninstall opencv_contrib_python
pip3 install opencv_contrib_python
^^^^
This solved the cv2.cv2 issue but then I'd get a new error:
"Could not find the Qt platform plugin "cocoa" in ""

To fix that:
pip3 uninstall opencv-python-headless
pip3 install opencv-python-headless

But then, I'd have the cv2.cv2 error again... so

pip3 uninstall opencv-contrib-python
pip3 uninstall opencv-python-headless
pip3 install opencv-contrib-python-headless

Hope it helps

**Comment by dubeyram** [comment]
This method Works for me.

I managed to make it work.
I uninstalled opencv-contrib using this command :

pip uninstall opencv_contrib_python

And reinstalled it using :

pip install opencv_contrib_python
